version: "3"
services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - target:/app/target
    depends_on:
      - db
    environment:
      ROCKET_ADDRESS: 0.0.0.0
      DATABASE_URL: postgres://stokepile:stokepile@db/stokepile_web
      STOKEPILE_BASE_URL: http://localhost:8000

  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: stokepile
      POSTGRES_PASSWORD: stokepile

volumes:
  target: {}
